# Prepopulated with the setup for eth-docker: https://github.com/eth-educators/eth-docker. You will have to change this if you setup a different way.

# Beacon client API
BEACON_API_URL="http://consensus:5052"  # eth-docker-consensus-1 (Port 9000)

# Execution client API
EXECUTION_API_URL="http://execution:8545"  # eth-docker-execution-1 (Port 8545, assuming it's the JSON-RPC API)

# Engine API
ENGINE_API_URL="http://execution:8551"  # eth-docker-execution-1 (Port 8545, assuming it's also the engine API)

# Engine API JWT
JWT_HEX="0x8d584b6fda83df471979118a63494d61ffd7084a149b33be3e0ab8ea92fb4bc9"  # To generate the JWT token run: openssl rand -hex 32 | tr -d "\n" > jwtsecret

# Fee recipient
FEE_RECIPIENT="0x675Fd297A916874d5518CC335f28b7a529A7c3Ac"  # Provide your Ethereum address for receiving fees

# The Interstate RPC port. This port must be exposed!
INTERSTATE_RPC_PORT="9061"  # eth-docker-mev-boost-1 (Port 8000)

# BLS commitment signing key
SIGNING_KEY="0x00bc72598d6ba483ec5aad004e1f7a59121f1a210bb26efe3d682e37e941c475"  # Provide the appropriate BLS key

# The validator indexes for which to accept commitments. Can be specified as a range i.e. "1..96" (includes 96)
VALIDATOR_INDEXES="64..79"  # Provide your validator indexes

# Bolt-enabled relay on Interstate
# INTERSTATE_RELAY="http://0xa55c1285d84ba83a5ad26420cd5ad3091e49c55a813eee651cd467db38a8c8e63192f47955e9376f6b42f6d190571cb5@162.55.190.235:35235"

# Genesis fork version for Interstate
GENESIS_FORK_VERSION="0x10000038"
