services:
  cb_pbs:
    image: interstatenetwork/interstate-pbs-module:0.2.1-dev
    # image: interstatenetwork/mev-boost:0.1.0-dev
    # image: bolt/bolt-boost:0.1.0-test
    container_name: cb_pbs
    ports:
      - 18550:18550
    environment:
      CB_CONFIG: /cb-config.toml
      METRICS_SERVER: 10000
    volumes:
      - ./cb-config.toml:/cb-config.toml:ro
    networks:
      kt-bolt-devnet:
      default:
        # cb_prometheus:
        #   image: prom/prometheus:latest
        #   container_name: cb_prometheus
        #   ports:
        #     - 9090:9090
        #   volumes:
        #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
        #     - ./targets.json:/etc/prometheus/targets.json
        #     - prometheus-data:/prometheus

        # cb_grafana:
        #   image: grafana/grafana:latest
        #   container_name: cb_grafana
        #   ports:
        #     - 3000:3000
        #   environment:
        #     - GF_SECURITY_ADMIN_PASSWORD=admin
        #   volumes:
        #     - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
        #     - ./grafana/datasources:/etc/grafana/provisioning/datasources
        #     - grafana-data:/var/lib/grafana
        #   depends_on:
        #     - cb_prometheus
        #   logging:
        #     driver: none

        # cb_cadvisor:
        #   image: gcr.io/cadvisor/cadvisor
        #   container_name: cb_cadvisor
        #   ports:
        #     - 8080:8080
        #   volumes:
        #     - type: bind
        #       source: /var/run/docker.sock
        #       target: /var/run/docker.sock
        #       read_only: true
        #       bind:
        #         propagation: rslave
        #     - type: bind
        #       source: /sys
        #       target: /sys
        #       read_only: true
        #       bind:
        #         propagation: rslave
        #     - type: bind
        #       source: /var/lib/docker/
        #       target: /var/lib/docker
        #       read_only: true
        #       bind:
        #         propagation: rslave
  
  # interstate-boost:
  #   # interstate-sidecar:
  #   image: interstatenetwork/interstate-boost:0.2.1-dev
  #   # image: bolt/bolt-sidecar:0.1.0-test
  #   container_name: interstate-boost
  #   # container_name: interstate-sidecar
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000" # Interstate RPC port (this should be opened on your firewall!)
  #     - "18551:18551"
  #   env_file: ./launch.env
  #   entrypoint: /bin/sh -c '/interstate-boost --port $$INTERSTATE_RPC_PORT --chain holesky --validator-indexes $$VALIDATOR_INDEXES --beacon-api-url $$BEACON_API_URL --execution-api-url $$EXECUTION_API_URL --engine-api-url $$ENGINE_API_URL --private-key $$SIGNING_KEY --mevboost-url http://cb_pbs:18550 --mevboost-proxy-port 18551 --jwt-hex $$JWT_HEX --fee-recipient $$FEE_RECIPIENT'
  #   # entrypoint: /bin/sh -c '/bolt-sidecar --port $$INTERSTATE_RPC_PORT --chain holesky --validator-indexes $$VALIDATOR_INDEXES --beacon-api-url $$BEACON_API_URL --execution-api-url $$EXECUTION_API_URL --engine-api-url $$ENGINE_API_URL --private-key $$SIGNING_KEY --constraints-url http://cb_pbs:18550 --constraints-proxy-port 18551 --jwt-hex $$JWT_HEX --fee-recipient $$FEE_RECIPIENT'
  #   networks:
  #     kt-interstate-devnet:
  #     default:
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
networks:
  kt-bolt-devnet:
    external: true
