services:
  interstate-sidecar:
    image: interstatenetwork/interstate-sidecar:0.1.0-alpha
    container_name: interstate-sidecar
    restart: unless-stopped
    ports:
      - "8000:8000" # Interstate RPC port (this should be opened on your firewall!)
      - "18551:18551" # MevBoost proxy port
    env_file: ./launch.env
    entrypoint: /bin/sh -c '/interstate-sidecar --port $$INTERSTATE_RPC_PORT --chain holesky --validator-indexes $$VALIDATOR_INDEXES --beacon-api-url $$BEACON_API_URL --execution-api-url $$EXECUTION_API_URL --engine-api-url $$ENGINE_API_URL --private-key $$SIGNING_KEY --mevboost-url http://cb-pbs:18550 --mevboost-proxy-port 18551 --jwt-hex $$JWT_HEX --fee-recipient $$FEE_RECIPIENT'
    networks:
      eth-docker_default:
      holesky_monitoring_network:

#   interstate-boost:
#     image: ghcr.io/chainbound/bolt-mev-boost:v0.2.1-alpha
#     container_name: interstate-boost
#     restart: unless-stopped
#     env_file: ./launch.env
#     entrypoint: /bin/sh -c '/app/mev-boost -relay-check -relay $$INTERSTATE_RELAY -addr 0.0.0.0:18550'
networks:
  eth-docker_default:
    external: true
  holesky_monitoring_network:
    external: true
