chain = "Holesky"

[pbs]
port = 18550
genesis_time_sec=1729245476

[[relays]]
url = "http://0xa55c1285d84ba83a5ad26420cd5ad3091e49c55a813eee651cd467db38a8c8e63192f47955e9376f6b42f6d190571cb5@162.55.190.235:35343"

[signer]
[signer.loader]
keys_path = "/work/register_validator/assigned_data/keys" # Fixed path to the keys folder to run validator
secrets_path = "/work/register_validator/assigned_data/secrets" # Fixed path to the secrets folder to run validator

[metrics]
prometheus_config = "./prometheus.yml"
