chain = "Holesky"

[pbs]
port = 18550

[[relays]]
url = "http://0xa55c1285d84ba83a5ad26420cd5ad3091e49c55a813eee651cd467db38a8c8e63192f47955e9376f6b42f6d190571cb5@37.27.37.181:9062"

[signer]
[signer.loader]
keys_path = "~/register_validator/assigned_data/keys" # Fixed path to the keys folder to run validator
secrets_path = "~/register_validator/assigned_data/secrets" # Fixed path to the secrets folder to run validator

[metrics]
prometheus_config = "./prometheus.yml"
